apiVersion: v2
name: csi-secrets-store-provider-azure
version: 1.6.0
appVersion: 1.6.0
kubeVersion: ">=1.16.0-0"
description: A Helm chart to install the Secrets Store CSI Driver and the Azure Keyvault Provider inside a Kubernetes cluster.
sources:
  - https://github.com/Azure/secrets-store-csi-driver-provider-azure
home: https://github.com/Azure/secrets-store-csi-driver-provider-azure
maintainers:
  - name: Anish Ramasekar
    email: anish.ramasekar@gmail.com
